### ISSUE TITLE
1.0.0-SNAPSHOT版本是否有连接未close（未归还连接池）的问题？

### ISSUE THREAD

**Issue by dongxurr123** [makersoft/mybatis-shards#26]
您好，我在公司的一份比较早期的工程中发现 有在使用这个框架的1.0.0-SNAPSHOT版本，使用的DBCP框架。这个应用在生产环境中，持续输出以下日志，该日志并不是异常，而是 DBCP针对被borrow出去的连接进行跟踪，如果超过一定时间未归还，则直接丢弃掉。这个堆栈代表的是该连接是哪次调用中申请的，不是普通异常中的堆栈。从这个可以看到应用是经过了mybatis-shards框架再到mybatis中申请的。

想和作者确认一下 是否有发现1.0.0-SNAPSHOT版本 中是否有此问题。borrow连接后未归还。

```log
org.apache.commons.dbcp.AbandonedTrace$AbandonedObjectException: DBCP object created 2023-02-03 16:50:35 by the following code was never closed:
at org.apache.commons.dbcp.AbandonedTrace.init(AbandonedTrace.java:90)
at org.apache.commons.dbcp.AbandonedTrace.<init>(AbandonedTrace.java:73)
at org.apache.commons.dbcp.DelegatingDatabaseMetaData.<init>(DelegatingDatabaseMetaData.java:52)
at org.apache.commons.dbcp.DelegatingConnection.getMetaData(DelegatingConnection.java:345)
at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.getMetaData(PoolingDataSource.java:245)
at net.sf.log4jdbc.ConnectionSpy.getMetaData(ConnectionSpy.java:298)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getNextResultSet(DefaultResultSetHandler.java:245)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:184)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy267.query(Unknown Source)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
at com.xx.bpo.common.page.PageableInterceptor.intercept(PageableInterceptor.java:84)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy266.query(Unknown Source)
at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
at com.xx.bpo.interceptor.TimerInterceptor.intercept(TimerInterceptor.java:50)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy266.query(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
at com.xx.bpo.common.page.PageableInterceptor.findCount(PageableInterceptor.java:217)
at com.xx.bpo.common.page.PageableInterceptor.intercept(PageableInterceptor.java:57)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy266.query(Unknown Source)
at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
at com.xx.bpo.interceptor.TimerInterceptor.intercept(TimerInterceptor.java:50)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy266.query(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.makersoft.shards.ShardImpl$SqlSessionInterceptor.invoke(ShardImpl.java:100)
at com.sun.proxy.$Proxy79.selectOne(Unknown Source)
at org.makersoft.shards.select.impl.ShardSelectImpl$2.execute(ShardSelectImpl.java:106)
at org.makersoft.shards.strategy.access.impl.SequentialShardAccessStrategy.apply(SequentialShardAccessStrategy.java:38)
at org.makersoft.shards.select.impl.ShardSelectImpl.getSingleResult(ShardSelectImpl.java:115)
at org.makersoft.shards.session.impl.ShardedSqlSessionImpl.selectOne(ShardedSqlSessionImpl.java:269)
at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown So
... 
```

**Comment by dongxurr123** [comment]
找到问题了，并非该框架的问题
